# Generated by Django 5.2.12 on 2026-03-28 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationcode_user_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50, verbose_name='限流场景')),
                ('bucket', models.CharField(max_length=255, verbose_name='限流桶')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='窗口开始时间')),
                ('last_attempt_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后尝试时间')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='封禁截至时间')),
            ],
            options={
                'verbose_name': '安全限流记录',
                'verbose_name_plural': '安全限流记录',
                'ordering': ('scope', 'bucket'),
                'indexes': [models.Index(fields=['scope', 'bucket'], name='accounts_se_scope_b06d83_idx'), models.Index(fields=['blocked_until'], name='accounts_se_blocked_08be8c_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'bucket'), name='accounts_securitythrottle_scope_bucket_uniq')],
            },
        ),
    ]
