# Generated by Django 5.2.12 on 2026-03-23 09:28

import base64
import hashlib
import hmac

from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations, models


def _key_material():
    return (getattr(settings, "CARD_SECRET_KEY", "") or settings.SECRET_KEY).encode("utf-8")


def _derive_digest(label):
    return hashlib.sha256(label.encode("utf-8") + b":" + _key_material()).digest()


def _fernet():
    return Fernet(base64.urlsafe_b64encode(_derive_digest("card-encryption")))


def _hash_secret(value):
    return hmac.new(_derive_digest("card-hash"), value.encode("utf-8"), hashlib.sha256).hexdigest()


def encrypt_existing_card_data(apps, schema_editor):
    CardCode = apps.get_model("shop", "CardCode")
    DeliveryRecord = apps.get_model("shop", "DeliveryRecord")
    fernet = _fernet()

    for card in CardCode.objects.all().iterator():
        plaintext = card.code or ""
        card.code_hash = _hash_secret(plaintext)
        if plaintext:
            card.code = fernet.encrypt(plaintext.encode("utf-8")).decode("utf-8")
        card.save(update_fields=["code", "code_hash"])

    for delivery in DeliveryRecord.objects.all().iterator():
        plaintext = delivery.display_code or ""
        if plaintext:
            delivery.display_code = fernet.encrypt(plaintext.encode("utf-8")).decode("utf-8")
            delivery.save(update_fields=["display_code"])


def decrypt_existing_card_data(apps, schema_editor):
    CardCode = apps.get_model("shop", "CardCode")
    DeliveryRecord = apps.get_model("shop", "DeliveryRecord")
    fernet = _fernet()

    for card in CardCode.objects.all().iterator():
        if card.code:
            card.code = fernet.decrypt(card.code.encode("utf-8")).decode("utf-8")
        card.code_hash = None
        card.save(update_fields=["code", "code_hash"])

    for delivery in DeliveryRecord.objects.all().iterator():
        if delivery.display_code:
            delivery.display_code = fernet.decrypt(delivery.display_code.encode("utf-8")).decode("utf-8")
            delivery.save(update_fields=["display_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_merchant_note_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcode',
            name='code_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True, verbose_name='卡密哈希'),
        ),
        migrations.AlterField(
            model_name='cardcode',
            name='code',
            field=models.TextField(verbose_name='卡密密文'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='display_code',
            field=models.TextField(verbose_name='交付密文'),
        ),
        migrations.RunPython(encrypt_existing_card_data, decrypt_existing_card_data),
    ]
