# Generated by Django 5.2.12 on 2026-03-23 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cardcode_code_hash_alter_cardcode_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action', models.CharField(choices=[('reveal_card_code', '查看库存卡密'), ('reveal_delivery_code', '查看发货内容'), ('send_delivery_reminder', '发送查看提醒')], max_length=40, verbose_name='操作类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源 IP')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_operation_logs', to=settings.AUTH_USER_MODEL)),
                ('card_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_logs', to='shop.cardcode')),
                ('delivery_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_logs', to='shop.deliveryrecord')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_logs', to='shop.order')),
            ],
            options={
                'verbose_name': '敏感操作日志',
                'verbose_name_plural': '敏感操作日志',
                'ordering': ('-created_at',),
            },
        ),
    ]
