# Generated by Django 5.2.12 on 2026-03-23 10:39

import django.db.models.deletion
import django.utils.timezone
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sensitiveoperationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ticket_no', models.CharField(default=shop.models.generate_support_ticket_no, max_length=32, unique=True, verbose_name='工单号')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('category', models.CharField(choices=[('order', '订单问题'), ('delivery', '发货问题'), ('payment', '支付问题'), ('account', '账号问题'), ('api', '接口问题'), ('aftersale', '售后处理'), ('other', '其他')], default='order', max_length=20, verbose_name='工单分类')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高')], default='normal', max_length=20, verbose_name='优先级')),
                ('subject', models.CharField(max_length=160, verbose_name='工单标题')),
                ('status', models.CharField(choices=[('pending_support', '待客服处理'), ('pending_user', '待用户回复'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending_support', max_length=20, verbose_name='工单状态')),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后消息时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('merchant_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='shop.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '客服工单',
                'verbose_name_plural': '客服工单',
                'ordering': ('-last_message_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sender_role', models.CharField(choices=[('user', '用户'), ('support', '客服'), ('system', '系统')], max_length=20, verbose_name='发送方角色')),
                ('body', models.TextField(verbose_name='消息内容')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.supportticket')),
            ],
            options={
                'verbose_name': '工单消息',
                'verbose_name_plural': '工单消息',
                'ordering': ('created_at',),
            },
        ),
    ]
